"""
HTML to PDF converter using PyMuPDF (pre-built wheels, zero system dependencies).
Cleans iXBRL/XBRL junk from SEC filings before conversion.
"""
import re
from io import BytesIO
from utils.server_logger import log_structured_error, log_error


def _clean_sec_html(html_content: str) -> str:
    """Strip XBRL metadata, scripts, hidden elements — keep readable HTML."""
    try:
        html_content = re.sub(r'<\?xml[^>]*\?>', '', html_content)
        html_content = re.sub(r'<!DOCTYPE[^>]*>', '', html_content, flags=re.IGNORECASE)
        html_content = re.sub(r'<script[^>]*>.*?</script>', '', html_content, flags=re.DOTALL | re.IGNORECASE)
        html_content = re.sub(r'<style[^>]*>.*?</style>', '', html_content, flags=re.DOTALL | re.IGNORECASE)
        html_content = re.sub(r'<ix:header[^>]*>.*?</ix:header>', '', html_content, flags=re.DOTALL | re.IGNORECASE)
        for _ in range(3):
            html_content = re.sub(
                r'<(div|span|p)[^>]*style=["\'][^"\']*display\s*:\s*none[^"\']*["\'][^>]*>.*?</\1>',
                '', html_content, flags=re.DOTALL | re.IGNORECASE
            )
        html_content = re.sub(r'<img[^>]*>', '', html_content, flags=re.IGNORECASE)
        html_content = re.sub(r'<ix:[^/][^>]*>', '', html_content, flags=re.IGNORECASE)
        html_content = re.sub(r'</ix:[^>]+>', '', html_content, flags=re.IGNORECASE)
        html_content = re.sub(r'<[a-z]+:[^>]*/>', '', html_content)
        html_content = re.sub(r'<[a-z]+:[^>]*>.*?</[a-z]+:[^>]*>', '', html_content, flags=re.DOTALL)
        html_content = re.sub(r'<[a-z]+:[^>]*>', '', html_content)
        html_content = re.sub(r'\s+(?:xmlns|xlink|xsi):[a-z]+="[^"]*"', '', html_content, flags=re.IGNORECASE)
        html_content = re.sub(r'\s+contextref="[^"]*"', '', html_content, flags=re.IGNORECASE)
        html_content = re.sub(r'\s+(?:unitref|decimals|scale|format|ix:[a-z]+)="[^"]*"', '', html_content, flags=re.IGNORECASE)
        return html_content
    except Exception as e:
        log_structured_error(e, page="html_to_pdf", component="_clean_sec_html", operation="cleaning_sec_html")
        return html_content  # Return original HTML rather than losing all content


def generate_filing_pdf(company_name: str, ticker: str, year: str,
                        doc_type: str, quarter: str, html_content: str) -> bytes:
    """
    Generate a branded PDF from SEC filing HTML using PyMuPDF.
    Pre-built wheels — no system libraries required.
    """
    try:
        import fitz

        clean_html = _clean_sec_html(html_content)

        period_label = f"{year} | {doc_type}"
        if quarter and quarter != "Annual":
            period_label += f" | {quarter}"

        full_html = f"""<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<style>
  body {{ font-family: Arial, sans-serif; font-size: 9pt; line-height: 1.5; color: #222; margin: 0; }}
  .cs-header {{ border-bottom: 3px solid #D62E2F; padding-bottom: 10px; margin-bottom: 14px; }}
  .cs-header h1 {{ color: #D62E2F; font-size: 15pt; margin: 0 0 3px 0; }}
  .cs-header .meta {{ color: #555; font-size: 9pt; }}
  .cs-header .note {{ color: #aaa; font-size: 7.5pt; margin-top: 3px; }}
  table {{ border-collapse: collapse; width: 100%; font-size: 8pt; margin: 8px 0; }}
  th, td {{ border: 1px solid #ccc; padding: 3px 5px; text-align: left; vertical-align: top; }}
  th {{ background: #f0f0f0; font-weight: bold; }}
  h1, h2, h3, h4 {{ color: #1a1a1a; margin-top: 12px; }}
  p {{ margin: 3px 0 6px 0; }}
  hr {{ border: none; border-top: 1px solid #ddd; margin: 8px 0; }}
</style>
</head>
<body>
<div class="cs-header">
  <h1>{company_name} ({ticker})</h1>
  <div class="meta">{period_label}</div>
  <div class="note">Generated by Coresight Research Portal</div>
</div>
<hr/>
{clean_html}
</body>
</html>"""

        buf = BytesIO()
        story = fitz.Story(html=full_html, em=9)
        writer = fitz.DocumentWriter(buf)
        mediabox = fitz.paper_rect("a4")
        margin = 50
        where = mediabox + (margin, margin, -margin, -margin)

        more = 1
        while more:
            device = writer.begin_page(mediabox)
            more, _ = story.place(where)
            story.draw(device)
            writer.end_page()

        writer.close()
        return buf.getvalue()
    except Exception as e:
        log_structured_error(e, page="html_to_pdf", component="generate_filing_pdf", operation="generating_html_to_pdf")
        return b""
